# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [12]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([0,0,0,1]).reshape(4,1)
y

array([[0],
       [0],
       [0],
       [1]])

In [10]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
# define syn1
syn1 = 2*np.random.random((3,1)) - 1

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）



神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [11]:
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l0,syn1))
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
    error = y - l2
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    # l1_delta = l1_error * nonlin(l1,True)
    l2_delta = error * nonlin(l2,True)
    

    #  以上已經把正向傳遞完成，所以要作反向傳遞... 

    # update weights
    
     # syn1 update weights
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    syn0 = syn0 + (l0.T).dot(l1_delta)
    syn1 += l1.T.dot(l2_delta)
    
print("Output After Training:")
print(l1)
print("\n\n")
print(l1)

Output After Training:
[[0.77352184 0.86377871 0.88122406]
 [0.69552942 0.74572968 0.75212425]
 [0.57700548 0.64873181 0.66096495]
 [0.47708756 0.46068103 0.4436154 ]]



[[0.77352184 0.86377871 0.88122406]
 [0.69552942 0.74572968 0.75212425]
 [0.57700548 0.64873181 0.66096495]
 [0.47708756 0.46068103 0.4436154 ]]
